apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGRnOXg2azR0
  CLOUDINARY_KEY: NjUyNzk2NzUxNjEyNDk2
  CLOUDINARY_SECRET: eVRWRTBac3ZicDk4WmIwVXE4Wms4WUpNYXdr
  MAPBOX_TOKEN: cGsuZXlKMUlqb2libUYyWldWdU9UZ2lMQ0poSWpvaVkyMXRkVzVqWXpJeE1YbDNiekp2YzJSMGQzVnVaSEJvYWlKOS4wdjh0UkI2RloyUzFPWFhoWUExWXF3
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAuZTZtcTRueS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
